services:
  ewm-stats:
    build:
      context: ./ewm-stats/server
    image: ewm-stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - ewm-stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-stats-db:5432/explore_with_me_stats
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  ewm-stats-db:
    image: postgres:16.1
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore_with_me_stats
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-main:
    build:
      context: ./ewm-main/
    image: ewm-main-server
    container_name: ewm-main-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-main-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-main-db:5432/explore_with_me_main
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  ewm-main-db:
    image: postgres:16.1
    container_name: ewm-main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=explore_with_me_main
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10