CREATE TABLE IF NOT EXISTS users (
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(250) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categories (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations (
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations (
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned BOOLEAN NOT NULL,
    title  VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    initiator_id       BIGINT REFERENCES users(id) NOT NULL,
    category_id        BIGINT REFERENCES categories(id) NOT NULL,
    location_id        BIGINT REFERENCES locations(id) NOT NULL,
    state              VARCHAR(30) NOT NULL,
    title              VARCHAR(120) NOT NULL,
    annotation         VARCHAR(2000) NOT NULL,
    description        VARCHAR(7000),
    paid               BOOLEAN NOT NULL,
    request_moderation BOOLEAN NOT NULL,
    participant_limit  BIGINT NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    event_date         TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE TABLE IF NOT EXISTS requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id BIGINT REFERENCES users(id) NOT NULL,
    event_id     BIGINT REFERENCES events(id) NOT NULL,
    status       VARCHAR(30) NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    CONSTRAINT unique_request UNIQUE (requester_id, event_id)
);

CREATE TABLE IF NOT EXISTS compilations_events (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id       BIGINT REFERENCES events(id) NOT NULL,
    compilation_id BIGINT REFERENCES compilations(id) NOT NULL
)